# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: detect-aws-credentials
    -   id: pretty-format-json
        args: [--autofix]

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6

-   repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
    -   id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

# -   repo: local
#     hooks:
#     -   id: tests
#         name: run tests
#         entry: docker
#         language: system
#         types: [python]
#         stages: [push]

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.740
#     hooks:
#     -   id: mypy
#         args: [--no-strict-optional, --ignore-missing-imports]
